version: '3'
services:
  rag-service:
    build:
      context: .
      dockerfile: rag-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
      - supabase
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    depends_on:
      - elasticsearch
      - supabase
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  supabase:
    image: supabase/postgres:latest
    environment:
      - POSTGRES_PASSWORD=supabase
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  esdata:
  pgdata:
