version: '3'
services:
  rag-service:
    image: rag-service:latest
    ports:
      - "8080:8080"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}

# docker-compose -f docker-compose-rag.yml up -d